# Cleaning a PostgreSQL Database
![Clean PostgreSQL Database](Project_Image.jpeg)

In this project, you will work with data from a hypothetical Super Store to challenge and enhance your SQL skills in data cleaning. This project will engage you in identifying top categories based on the highest profit margins and detecting missing values, utilizing your comprehensive knowledge of SQL concepts.

## Data Dictionary:

### `orders`:
| Column | Definition | Data type | Comments |
|--------|------------|-----------|----------|
| `row_id`| Unique Record ID | `INTEGER` |
| `order_id` | Identifier for each order in table | `TEXT` | Connects to `order_id` in `returned_orders` table |
| `order_date` | Date when order was placed | `TEXT` |
| `market` | Market order_id belongs to | `TEXT` |
| `region` | Region Customer belongs to | `TEXT` | Connects to `region` in `people` table |
| `product_id` | Identifier of Product bought | `TEXT` | Connects to `product_id` in `products` table |
| `sales` | Total Sales Amount for the Line Item | `DOUBLE PRECISION` |
| `quantity` | Total Quantity for the Line Item | `DOUBLE PRECISION` |
| `discount` | Discount applied for the Line Item | `DOUBLE PRECISION` |
| `profit` | Total Profit earned on the Line Item | `DOUBLE PRECISION` |

### `returned_orders`:
| Column | Definition | Data type |
|--------|------------|-----------|
| `returned`| Yes values for Order / Line Item Returned | `TEXT` |
| `order_id` | Identifier for each order in table | `TEXT` |
| `market` | Market order_id belongs to | `TEXT` |

### `people`:
| Column | Definition | Data type |
|--------|------------|-----------|
| `person`| Name of Salesperson credited with Order | `TEXT` |
| `region` | Region Salesperson in operating in | `TEXT` |

### `products`:
| Column | Definition | Data type |
|--------|------------|-----------|
| `product_id`| Unique Identifier for the Product | `TEXT` |
| `category` | Category Product belongs to | `TEXT` |
| `sub_category` | Sub Category Product belongs to | `TEXT` |
| `product_name` | Detailed Name of the Product | `TEXT` |

As you can see in the Data Dictionary above, date fields have been written to the `orders` table as `TEXT` and numeric fields like sales, profit, etc. have been written to the `orders` table as `Double Precision`. You will need to take care of these types in some of the queries. This project is an excellent opportunity to apply your SQL skills in a practical setting and gain valuable experience in data cleaning and analysis. Good luck, and happy querying!

In [20]:
-- top_five_products_each_category
WITH top_product_each_category AS (
	SELECT p.category AS category, 
		 p.product_name AS product_name, 
		 SUM(o.sales)::NUMERIC AS product_total_sales, 
		 SUM(o.profit)::NUMERIC AS product_total_profit,
		 RANK() OVER(PARTITION BY p.category ORDER BY SUM(o.sales) DESC) AS product_rank
    FROM products as p
    LEFT JOIN orders as o
    USING(product_id)
    GROUP BY p.category, p.product_name
)

-- top_five_products_each_category
SELECT category,
	product_name,
	ROUND(product_total_sales, 2) AS product_total_sales,
	ROUND(product_total_profit, 2) AS product_total_profit,
	product_rank
FROM top_product_each_category
WHERE product_rank <= 5
ORDER BY category

           category  ... product_rank
0         Furniture  ...            1
1         Furniture  ...            2
2         Furniture  ...            3
3         Furniture  ...            4
4         Furniture  ...            5
5   Office Supplies  ...            1
6   Office Supplies  ...            2
7   Office Supplies  ...            3
8   Office Supplies  ...            4
9   Office Supplies  ...            5
10       Technology  ...            1
11       Technology  ...            2
12       Technology  ...            3
13       Technology  ...            4
14       Technology  ...            5

[15 rows x 5 columns]

In [21]:
-- impute_missing_values
WITH unit_price_cte AS (
	SELECT product_id,
		   discount,
		   market,
		   region,
		   SUM(sales)/SUM(quantity::NUMERIC) AS unit_price
	FROM orders 
	WHERE quantity IS NOT NULL
	GROUP BY product_id, discount, market, region
),

imputed_missing_values AS (
	SELECT o.product_id,
	o.discount,
	o.market,
	o.region,
	o.sales,
	o.quantity,
    CASE 
		WHEN quantity IS NULL THEN sales/unit_price
	    ELSE quantity END AS calculated_quantity
FROM orders AS o
LEFT JOIN unit_price_cte AS upc
		ON o.product_id = upc.product_id
        AND o.discount = upc.discount
        AND o.market = upc.market
        AND o.region = upc.region
WHERE quantity IS NULL
)

SELECT *
FROM imputed_missing_values
ORDER BY product_id, discount, market, region;

         product_id  discount  market  ...    sales  quantity  calculated_quantity
0  FUR-ADV-10000571      0.00    EMEA  ...  438.960       NaN                  4.0
1  FUR-ADV-10004395      0.00    EMEA  ...   84.120       NaN                  2.0
2   FUR-BO-10001337      0.15      US  ...  308.499       NaN                  3.0
3  TEC-STA-10003330      0.00  Africa  ...  506.640       NaN                  2.0
4  TEC-STA-10004542      0.00  Africa  ...  160.320       NaN                  4.0

[5 rows x 7 columns]

In [1]:
SELECT * FROM public.orders

       row_id        order_id  ... shipping_cost order_priority
0         957  MX-2014-105921  ...        21.713         Medium
1       24359   ID-2013-61442  ...        21.710            Low
2       32298  CA-2012-124891  ...       933.570       Critical
3       26341   IN-2013-77878  ...       923.630       Critical
4       25330   IN-2013-71249  ...       915.490         Medium
...       ...             ...  ...           ...            ...
51285   29002   IN-2014-62366  ...         0.010         Medium
51286   35398  US-2014-102288  ...         0.010         Medium
51287   40470  US-2013-155768  ...         0.010           High
51288    9596  MX-2012-140767  ...         0.003         Medium
51289    6147  MX-2012-134460  ...         0.002           High

[51290 rows x 21 columns]

In [6]:
SELECT * FROM public.products

             product_id  ...                                       product_name
0       TEC-AC-10003033  ...  Plantronics CS510 - Over-the-Head monaural Wir...
1       FUR-CH-10003950  ...          Novimex Executive Leather Armchair, Black
2       TEC-PH-10004664  ...                  Nokia Smart Phone, with Caller ID
3       TEC-PH-10004583  ...                     Motorola Smart Phone, Cordless
4      TEC-SHA-10000501  ...                     Sharp Wireless Fax, High-Speed
...                 ...  ...                                                ...
10287   OFF-FA-10004112  ...                         Stockwell Staples, 12 Pack
10288   OFF-BI-10003253  ...                           Ibico Index Tab, Economy
10289   OFF-BI-10002510  ...                              Acco Index Tab, Clear
10290  FUR-ADV-10002329  ...                     Advantus Light Bulb, Erganomic
10291   OFF-AP-10002203  ...  Eureka Disposable Bags for Sanitaire Vibra Gro...

[10292 rows x 4 columns]

In [5]:
SELECT * FROM public.people

            region                person
0          Central         Anna Andreadi
1            South           Chuck Magee
2             East        Kelly Williams
3             West        Matt Collister
4           Africa     Deborah Brumfield
5             EMEA          Larry Hughes
6           Canada         Nicole Hansen
7        Caribbean      Giulietta Dortch
8     Central Asia            Nora Preis
9            North           Jack Lebron
10      North Asia       Shirley Daniels
11         Oceania        Anthony Jacobs
12  Southeast Asia  Alejandro Ballentine

In [1]:
SELECT * FROM public.people

            region                person
0          Central         Anna Andreadi
1            South           Chuck Magee
2             East        Kelly Williams
3             West        Matt Collister
4           Africa     Deborah Brumfield
5             EMEA          Larry Hughes
6           Canada         Nicole Hansen
7        Caribbean      Giulietta Dortch
8     Central Asia            Nora Preis
9            North           Jack Lebron
10      North Asia       Shirley Daniels
11         Oceania        Anthony Jacobs
12  Southeast Asia  Alejandro Ballentine

In [4]:
SELECT * FROM public.returned_orders

     returned         order_id         market
0         Yes   MX-2013-168137          LATAM
1         Yes   US-2011-165316          LATAM
2         Yes  ES-2013-1525878             EU
3         Yes   CA-2013-118311  United States
4         Yes  ES-2011-1276768             EU
...       ...              ...            ...
1168      Yes  ES-2013-2639112             EU
1169      Yes   CA-2014-134194  United States
1170      Yes  ES-2012-3246286             EU
1171      Yes  ES-2012-4379168             EU
1172      Yes   CA-2014-168193  United States

[1173 rows x 3 columns]